-- scripts/broll_output/seed_broll_clips.sql
-- Generated by scripts/broll_harvest.py
--
-- BEFORE RUNNING:
--   1. Upload each final_clips/*.mp4 to R2 via boto3 (credentialed, no presigned URLs).
--   2. Replace placeholder r2_url values below with actual adcreo-assets/broll/... paths.
--   3. Update negative_space_score for non-cta_bg rows after visual review (default=5).
--   4. Update archetype column if needed (default='texture').
--
-- AFTER RUNNING:
--   SELECT category, role, COUNT(*) FROM broll_clips
--   WHERE is_active=TRUE GROUP BY 1,2 ORDER BY 1,2;

BEGIN;

-- d2c_beauty__hook_1
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'd2c_beau_hook_1',
  'texture',
  'd2c_beauty',
  3000,
  'adcreo-assets/broll/d2c_beauty/d2c_beauty__hook_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_16478020',
  TRUE,
  'hook',
  'active',
  'warm',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- d2c_beauty__hook_2
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'd2c_beau_hook_2',
  'texture',
  'd2c_beauty',
  3000,
  'adcreo-assets/broll/d2c_beauty/d2c_beauty__hook_2.mp4',
  TRUE, TRUE, TRUE,
  'pexels_10532909',
  TRUE,
  'hook',
  'intense',
  'warm',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- d2c_beauty__context
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'd2c_beau_cont_1',
  'texture',
  'd2c_beauty',
  3000,
  'adcreo-assets/broll/d2c_beauty/d2c_beauty__context_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_20349690',
  TRUE,
  'context',
  'calm',
  'warm',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- d2c_beauty__cta_bg
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'd2c_beau_cta__1',
  'texture',
  'd2c_beauty',
  3000,
  'adcreo-assets/broll/d2c_beauty/d2c_beauty__cta_bg_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_8516623',
  TRUE,
  'cta_bg',
  'calm',
  'warm',
  7,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- packaged_food__hook_1
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'packaged_hook_1',
  'texture',
  'packaged_food',
  3000,
  'adcreo-assets/broll/packaged_food/packaged_food__hook_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_8597293',
  TRUE,
  'hook',
  'active',
  'warm',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- packaged_food__context
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'packaged_cont_1',
  'texture',
  'packaged_food',
  3000,
  'adcreo-assets/broll/packaged_food/packaged_food__context_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_10071214',
  TRUE,
  'context',
  'calm',
  'warm',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- packaged_food__cta_bg
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'packaged_cta__1',
  'texture',
  'packaged_food',
  3000,
  'adcreo-assets/broll/packaged_food/packaged_food__cta_bg_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_7045895',
  TRUE,
  'cta_bg',
  'calm',
  'warm',
  7,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- electronics__hook_1
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'electron_hook_1',
  'texture',
  'electronics',
  3000,
  'adcreo-assets/broll/electronics/electronics__hook_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_3712700',
  TRUE,
  'hook',
  'active',
  'cool',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- electronics__hook_2
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'electron_hook_2',
  'texture',
  'electronics',
  3000,
  'adcreo-assets/broll/electronics/electronics__hook_2.mp4',
  TRUE, TRUE, TRUE,
  'pexels_14209120',
  TRUE,
  'hook',
  'intense',
  'cool',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- electronics__context
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'electron_cont_1',
  'texture',
  'electronics',
  3000,
  'adcreo-assets/broll/electronics/electronics__context_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_12257306',
  TRUE,
  'context',
  'calm',
  'cool',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- electronics__cta_bg
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'electron_cta__1',
  'texture',
  'electronics',
  3000,
  'adcreo-assets/broll/electronics/electronics__cta_bg_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_3755074',
  TRUE,
  'cta_bg',
  'calm',
  'cool',
  7,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- hard_accessories__hook_1
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'hard_acc_hook_1',
  'texture',
  'hard_accessories',
  3000,
  'adcreo-assets/broll/hard_accessories/hard_accessories__hook_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_7829858',
  TRUE,
  'hook',
  'active',
  'neutral',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- hard_accessories__hook_2
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'hard_acc_hook_2',
  'texture',
  'hard_accessories',
  3000,
  'adcreo-assets/broll/hard_accessories/hard_accessories__hook_2.mp4',
  TRUE, TRUE, TRUE,
  'pexels_5678004',
  TRUE,
  'hook',
  'intense',
  'neutral',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- hard_accessories__context
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'hard_acc_cont_1',
  'texture',
  'hard_accessories',
  3000,
  'adcreo-assets/broll/hard_accessories/hard_accessories__context_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_6278961',
  TRUE,
  'context',
  'calm',
  'neutral',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- hard_accessories__cta_bg
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'hard_acc_cta__1',
  'texture',
  'hard_accessories',
  3000,
  'adcreo-assets/broll/hard_accessories/hard_accessories__cta_bg_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_9603572',
  TRUE,
  'cta_bg',
  'calm',
  'neutral',
  7,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- home_kitchen__hook_2
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'home_kit_hook_2',
  'texture',
  'home_kitchen',
  3000,
  'adcreo-assets/broll/home_kitchen/home_kitchen__hook_2.mp4',
  TRUE, TRUE, TRUE,
  'pexels_7830747',
  TRUE,
  'hook',
  'intense',
  'warm',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- home_kitchen__context
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'home_kit_cont_1',
  'texture',
  'home_kitchen',
  3000,
  'adcreo-assets/broll/home_kitchen/home_kitchen__context_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_6278959',
  TRUE,
  'context',
  'calm',
  'warm',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- home_kitchen__cta_bg
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'home_kit_cta__1',
  'texture',
  'home_kitchen',
  3000,
  'adcreo-assets/broll/home_kitchen/home_kitchen__cta_bg_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_20349691',
  TRUE,
  'cta_bg',
  'calm',
  'warm',
  7,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- d2c_fashion__hook_1
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'd2c_fash_hook_1',
  'texture',
  'd2c_fashion',
  3000,
  'adcreo-assets/broll/d2c_fashion/d2c_fashion__hook_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_7233560',
  TRUE,
  'hook',
  'active',
  'neutral',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- d2c_fashion__context
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'd2c_fash_cont_1',
  'texture',
  'd2c_fashion',
  3000,
  'adcreo-assets/broll/d2c_fashion/d2c_fashion__context_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_8102655',
  TRUE,
  'context',
  'calm',
  'neutral',
  5,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

-- d2c_fashion__cta_bg
INSERT INTO broll_clips (
  clip_id, archetype, category, duration_ms, r2_url,
  excludes_faces, excludes_hands, excludes_locations,
  license_ref, is_active,
  role, mood_energy, mood_temperature,
  negative_space_score, seasonality_tags, brand_tier_fit
) VALUES (
  'd2c_fash_cta__1',
  'texture',
  'd2c_fashion',
  3000,
  'adcreo-assets/broll/d2c_fashion/d2c_fashion__cta_bg_1.mp4',
  TRUE, TRUE, TRUE,
  'pexels_10527009',
  TRUE,
  'cta_bg',
  'calm',
  'neutral',
  7,
  '{}',
  '{mass,premium,luxury}'
) ON CONFLICT (clip_id) DO NOTHING;

COMMIT;
